In [32]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import  train_test_split

In [33]:
df=pd.read_csv('/home/rockbot/Documents/Data_Structure_py/conAI/USA_Housing.csv')
df

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0          79545.45857             5.682861                   7.009188   
1          79248.64245             6.002900                   6.730821   
2          61287.06718             5.865890                   8.512727   
3          63345.24005             7.188236                   5.586729   
4          59982.19723             5.040555                   7.839388   
...                ...                  ...                        ...   
4995       60567.94414             7.830362                   6.137356   
4996       78491.27543             6.999135                   6.576763   
4997       63390.68689             7.250591                   4.805081   
4998       68001.33124             5.534388                   7.130144   
4999       65510.58180             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  
0                             4.09      23086.80050  1.059034e+06  
1                             3.09      40173.07217  1.505891e+06  
2                             5.13      36882.15940  1.058988e+06  
3                             3.26      34310.24283  1.260617e+06  
4                             4.23      26354.10947  6.309435e+05  
...                            ...              ...           ...  
4995                          3.46      22837.36103  1.060194e+06  
4996                          4.02      25616.11549  1.482618e+06  
4997                          2.13      33266.14549  1.030730e+06  
4998                          5.44      42625.62016  1.198657e+06  
4999                          4.07      46501.28380  1.298950e+06  

[5000 rows x 6 columns]

In [34]:
X=df.iloc[:,:5]
Y=df.iloc[:,5]

In [35]:
stdsc=StandardScaler()
X_scaled = stdsc.fit_transform(X)
print(X_scaled)

[[ 1.02865969 -0.29692705  0.02127433  0.08806222 -1.31759867]
 [ 1.00080775  0.02590164 -0.25550611 -0.72230146  0.40399945]
 [-0.68462915 -0.11230283  1.5162435   0.93084045  0.07240989]
 ...
 [-0.48723454  1.28447022 -2.17026949 -1.50025059 -0.29193658]
 [-0.05459152 -0.44669439  0.14154061  1.18205319  0.65111608]
 [-0.28831272  0.01521477 -0.19434166  0.07185495  1.04162464]]


In [36]:
X_new=np.insert(X_scaled,1,0,1)
print(X_new)

[[ 1.02865969  0.         -0.29692705  0.02127433  0.08806222 -1.31759867]
 [ 1.00080775  0.          0.02590164 -0.25550611 -0.72230146  0.40399945]
 [-0.68462915  0.         -0.11230283  1.5162435   0.93084045  0.07240989]
 ...
 [-0.48723454  0.          1.28447022 -2.17026949 -1.50025059 -0.29193658]
 [-0.05459152  0.         -0.44669439  0.14154061  1.18205319  0.65111608]
 [-0.28831272  0.          0.01521477 -0.19434166  0.07185495  1.04162464]]


In [37]:
size = len(df.index)
fold_count = 5
chunk_size = size//5
fold_lst = []
total_chunk = list(df.index)
for x in range(fold_count):
    test_lst = np.arange(x*chunk_size,(x+1)*chunk_size)
    train_lst = np.arange(0,x*chunk_size)
    train_lst = np.concatenate((train_lst, np.arange((x+1)*chunk_size, size)))
    fold_lst.append((test_lst,train_lst))
len(fold_lst)

5

In [38]:
def r2_error(Y_predict, Y_test):
    err = Y_predict-Y_test
    sse = np.sum(err**2)
    Y_mean = np.mean(Y_test)
    tot_var = np.sum((Y_test-Y_mean)**2)
    r2e = 1-sse/tot_var
    return r2e
def solveBeta(X, Y):
    A = X.T.dot(X)
    B = np.linalg.inv(A)
    C = B.dot(X.T)
    beta = C.dot(Y)
    return beta

In [39]:
def predict(X, beta):
    Y_predict = X.dot(beta)
    return Y_predict

In [40]:
score_lst = []
beta_lst = []
for test_idx, train_idx in fold_lst:
    X_train,X_test,Y_train,Y_test = X_new[train_idx],X_new[test_idx],Y[train_idx],Y[test_idx]
    beta = solveBeta(X_train,Y_train)
    beta_lst.append(beta)
    Y_predict = predict(X_test, beta)
    R2err = r2_error(Y_predict, Y_test)
    score_lst.append(R2err)
print(score_lst)

LinAlgError: Singular matrix

In [ ]:
max_score = max(score_lst)
max_idx = score_lst.index(max_score)
best_beta = beta_lst[max_idx]
print(best_beta)

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X_new,Y,test_size=0.3,random_state = 41)
Y_predict = predict(X_test, best_beta)
R2err = r2_error(Y_predict, Y_test)
print(R2err)