In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/home/rockbot/Documents/Data_Structure_py/mlLab/mlLab code/ConAi/IMDBDataset.csv",nrows=500)
df=df.drop('sentiment',axis=1)
df

review
0    One of the other reviewers has mentioned that ...
1    A wonderful little production. <br /><br />The...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
..                                                 ...
495  "American Nightmare" is officially tied, in my...
496  First off, I have to say that I loved the book...
497  This movie was extremely boring. I only laughe...
498  I was disgusted by this movie. No it wasn't be...
499  Such a joyous world has been created for us in...

[500 rows x 1 columns]

In [3]:
corpus=[]
for i in range(len(df)):
    corpus.append(df['review'][i])

In [4]:
corpus_final=[]
for i in range(len(corpus)):
    corpus_final.append(" ".join([word.lower() for word in corpus[i].split() if word.isalpha()]))
corpus_final

['one of the other reviewers has mentioned that after watching just oz episode be they are as this is exactly what happened with first thing that struck me about oz was its brutality and unflinching scenes of which set in right from the word trust this is not a show for the faint hearted or this show pulls no punches with regards to sex or its is in the classic use of the is called oz as that is the nickname given to the oswald maximum security state it focuses mainly on emerald an experimental section of the prison where all the cells have glass fronts and face so privacy is not high on the em city is home to irish and death dodgy dealings and shady agreements are never far would say the main appeal of the show is due to the fact that it goes where other shows forget pretty pictures painted for mainstream forget forget mess the first episode i ever saw struck me as so nasty it was i say i was ready for but as i watched i developed a taste for and got accustomed to the high levels of g

In [5]:
document_frequency={}
for i in range(len(corpus_final)):
    word_frequency={}
    for word in corpus_final[i].split():
        word_frequency[word]=1
    document_frequency[i]=word_frequency

In [6]:
bow=pd.DataFrame(document_frequency)
bow.fillna(0,inplace=True)
bow

0    1    2    3    4    5    6    7    8    9    ...  490  \
one            1.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0  ...  1.0   
of             1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  ...  1.0   
the            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  ...  1.0   
other          1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
reviewers      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
...            ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
insects        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
mirth          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
dazzling       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
abundant       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
incredulously  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   

               491  492  493  494  495  496  497  498  499  
one            1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  
of             1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
the            1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
other          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
reviewers      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...            ...  ...  ...  ...  ...  ...  ...  ...  ...  
insects        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
mirth          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
dazzling       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
abundant       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
incredulously  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  

[10354 rows x 500 columns]

In [7]:
cooccurence_matrix=bow.values.dot(bow.values.T)

In [8]:
np.fill_diagonal(cooccurence_matrix,0)

In [9]:
cooccurence_matrix

array([[  0., 247., 250., ...,   1.,   1.,   1.],
       [247.,   0., 477., ...,   1.,   1.,   1.],
       [250., 477.,   0., ...,   1.,   1.,   1.],
       ...,
       [  1.,   1.,   1., ...,   0.,   1.,   1.],
       [  1.,   1.,   1., ...,   1.,   0.,   1.],
       [  1.,   1.,   1., ...,   1.,   1.,   0.]])

In [10]:
cooccurence_matrix.shape

(10354, 10354)

In [11]:
cooccurence_matrix_t=cooccurence_matrix.T
cooccurence_matrix

array([[  0., 247., 250., ...,   1.,   1.,   1.],
       [247.,   0., 477., ...,   1.,   1.,   1.],
       [250., 477.,   0., ...,   1.,   1.,   1.],
       ...,
       [  1.,   1.,   1., ...,   0.,   1.,   1.],
       [  1.,   1.,   1., ...,   1.,   0.,   1.],
       [  1.,   1.,   1., ...,   1.,   1.,   0.]])

In [12]:
x=cooccurence_matrix.dot(cooccurence_matrix_t)
x

array([[1.813243e+06, 3.112886e+06, 3.190434e+06, ..., 1.177000e+04,
        1.177000e+04, 1.177000e+04],
       [3.112886e+06, 5.636498e+06, 5.552165e+06, ..., 2.036900e+04,
        2.036900e+04, 2.036900e+04],
       [3.190434e+06, 5.552165e+06, 5.927874e+06, ..., 2.083700e+04,
        2.083700e+04, 2.083700e+04],
       ...,
       [1.177000e+04, 2.036900e+04, 2.083700e+04, ..., 3.540000e+02,
        3.530000e+02, 3.530000e+02],
       [1.177000e+04, 2.036900e+04, 2.083700e+04, ..., 3.530000e+02,
        3.540000e+02, 3.530000e+02],
       [1.177000e+04, 2.036900e+04, 2.083700e+04, ..., 3.530000e+02,
        3.530000e+02, 3.540000e+02]])

In [13]:
x.shape

(10354, 10354)

In [14]:
eig_val,eig_vector=np.linalg.eig(x)

In [15]:
print(eig_val)

[1.75853692e+08+0.j 2.81199552e+05+0.j 2.39895909e+05+0.j ...
 1.00000000e+00+0.j 1.00000000e+00+0.j 1.00000000e+00+0.j]


In [16]:
print(eig_vector)

[[-1.00713013e-01+0.j -1.28296447e-02+0.j -2.18101248e-04+0.j ...
  -2.27910848e-15+0.j  1.27835113e-15+0.j -1.47976077e-15+0.j]
 [-1.75892547e-01+0.j -1.09708400e-01+0.j -1.45462666e-01+0.j ...
  -2.13361998e-16+0.j -2.47870822e-15+0.j -8.57347911e-16+0.j]
 [-1.80185572e-01+0.j -1.20794391e-01+0.j  9.06843505e-01+0.j ...
  -1.19987664e-15+0.j  3.42353626e-16+0.j -1.65275082e-15+0.j]
 ...
 [-6.65027944e-04+0.j  5.68644972e-03+0.j -3.84952401e-06+0.j ...
  -5.96252919e-03+0.j  6.24108797e-04+0.j  1.27128035e-02+0.j]
 [-6.65027944e-04+0.j  5.68644972e-03+0.j -3.84952401e-06+0.j ...
   2.81521269e-03+0.j -4.42120932e-04+0.j  2.82975647e-03+0.j]
 [-6.65027944e-04+0.j  5.68644972e-03+0.j -3.84952401e-06+0.j ...
   9.90883155e-05+0.j -6.51015361e-03+0.j  4.02075436e-03+0.j]]


In [18]:
vec=eig_vector[:500]
vec

array([[-1.00713013e-01+0.j, -1.28296447e-02+0.j, -2.18101248e-04+0.j,
        ..., -2.27910848e-15+0.j,  1.27835113e-15+0.j,
        -1.47976077e-15+0.j],
       [-1.75892547e-01+0.j, -1.09708400e-01+0.j, -1.45462666e-01+0.j,
        ..., -2.13361998e-16+0.j, -2.47870822e-15+0.j,
        -8.57347911e-16+0.j],
       [-1.80185572e-01+0.j, -1.20794391e-01+0.j,  9.06843505e-01+0.j,
        ..., -1.19987664e-15+0.j,  3.42353626e-16+0.j,
        -1.65275082e-15+0.j],
       ...,
       [-6.78590977e-03+0.j, -1.32948791e-03+0.j,  2.39506817e-05+0.j,
        ...,  2.02658329e-15+0.j,  1.04116836e-15+0.j,
         1.16655637e-15+0.j],
       [-2.94510884e-02+0.j,  1.80498380e-02+0.j,  1.47492726e-03+0.j,
        ...,  2.54789214e-16+0.j,  1.24767731e-15+0.j,
         7.49160577e-16+0.j],
       [-2.01714598e-02+0.j, -5.54963013e-02+0.j,  1.35524572e-03+0.j,
        ...,  3.48846993e-15+0.j,  4.04180939e-16+0.j,
        -3.16092398e-16+0.j]])

In [20]:
word_vector=vec.dot(cooccurence_matrix)
word_vector

array([[-9.43808761e+01-2.78815398e-13j, -1.85026359e+02-2.54972315e-13j,
        -1.95869046e+02-2.92200012e-13j, ...,
        -3.22867959e-01-1.11353304e-14j, -3.22867959e-01-1.11353304e-14j,
        -3.22867959e-01-1.11353304e-14j],
       [ 4.28733310e+01-1.39564225e-13j,  7.90461247e+01-1.84229178e-13j,
         1.00091728e+02-1.96744394e-13j, ...,
         5.13445259e-01-1.36260935e-14j,  5.13445259e-01-1.36260935e-14j,
         5.13445259e-01-1.36260935e-14j],
       [ 2.36579212e+02-7.52954017e-15j,  4.61387626e+02+1.47352252e-13j,
        -2.72887686e+01+1.44722846e-13j, ...,
         8.33676875e-01-8.30133850e-15j,  8.33676875e-01-8.30133850e-15j,
         8.33676875e-01-8.30133850e-15j],
       ...,
       [-4.17380106e+01-2.15847574e-13j, -7.53940333e+01-1.79051396e-13j,
        -7.74720376e+01-2.08730739e-13j, ...,
        -3.62423601e-01-4.16167088e-15j, -3.62423601e-01-4.16167088e-15j,
        -3.62423601e-01-4.16167088e-15j],
       [-7.79763197e+01+1.42396526e-14j, -1.

In [21]:
word_vector.shape

(500, 10354)

In [30]:
df1=pd.DataFrame(word_vector)
df1

0                     1                     2      \
0    -94.380876-0.000000j -185.026359-0.000000j -195.869046-0.000000j   
1     42.873331-0.000000j   79.046125-0.000000j  100.091728-0.000000j   
2    236.579212-0.000000j  461.387626+0.000000j  -27.288769+0.000000j   
3     55.740077-0.000000j   72.063716-0.000000j   91.895431-0.000000j   
4    5.0214600-0.0000000j  9.7488580-0.0000000j  8.1445860-0.0000000j   
..                    ...                   ...                   ...   
495  -21.525360-0.000000j  -70.775324-0.000000j  -44.908453-0.000000j   
496   47.419389-0.000000j   68.343137-0.000000j   72.878961-0.000000j   
497  -41.738011-0.000000j  -75.394033-0.000000j  -77.472038-0.000000j   
498  -77.976320+0.000000j -159.895682-0.000000j -156.392033-0.000000j   
499  -70.429781+0.000000j -103.342694+0.000000j -134.432691+0.000000j   

                   3                   4                     5      \
0   -50.725045+0.000000j -0.930161-0.000000j  -87.356338-0.000000j   
1    11.434247-0.000000j  1.039471+0.000000j  -28.538261-0.000000j   
2     107.50209+0.00000j  2.881230-0.000000j  166.315526+0.000000j   
3    24.366835+0.000000j  0.310369-0.000000j   44.415504-0.000000j   
4     3.630427+0.000000j -0.029007-0.000000j  4.0267160+0.0000000j   
..                   ...                 ...                   ...   
495 -14.682554-0.000000j -1.011867+0.000000j  -20.607045-0.000000j   
496  25.558915+0.000000j  0.534863-0.000000j   37.833863+0.000000j   
497 -25.339173-0.000000j -0.668534+0.000000j  -38.120332+0.000000j   
498 -40.130962-0.000000j -0.308504-0.000000j  -60.527278-0.000000j   
499 -34.670114-0.000000j -1.144463+0.000000j  -62.058133+0.000000j   

                  6                     7                    8      \
0   -6.465685-0.000000j -155.039119-0.000000j -43.042463-0.000000j   
1    4.239849-0.000000j   18.319994-0.000000j  15.087248-0.000000j   
2     12.06282-0.00000j  321.157882+0.000000j  95.261607+0.000000j   
3    0.557602+0.000000j   71.882636-0.000000j  24.432234-0.000000j   
4    0.359130+0.000000j  7.6035850+0.0000000j   4.128868+0.000000j   
..                  ...                   ...                  ...   
495 -1.412138-0.000000j  -40.693302-0.000000j -14.780094-0.000000j   
496  3.100338-0.000000j   61.498791+0.000000j  16.684157-0.000000j   
497 -2.123175-0.000000j  -66.322840-0.000000j -21.690644-0.000000j   
498 -3.036821+0.000000j -126.331508-0.000000j -38.922012+0.000000j   
499 -5.388378+0.000000j -110.236203+0.000000j -36.402027+0.000000j   

                   9      ...               10344               10345  \
0   -27.992066-0.000000j  ... -0.322868-0.000000j -0.322868-0.000000j   
1     3.402875-0.000000j  ...  0.513445-0.000000j  0.513445-0.000000j   
2    57.708138+0.000000j  ...  0.833677-0.000000j  0.833677-0.000000j   
3    12.484032+0.000000j  ...  0.017143+0.000000j  0.017143+0.000000j   
4     0.634153-0.000000j  ...  0.131045-0.000000j  0.131045-0.000000j   
..                   ...  ...                 ...                 ...   
495  -7.769932-0.000000j  ... -0.408800-0.000000j -0.408800-0.000000j   
496   9.096506-0.000000j  ...  0.951863-0.000000j  0.951863-0.000000j   
497 -12.482537+0.000000j  ... -0.362424-0.000000j -0.362424-0.000000j   
498 -24.453049+0.000000j  ... -0.562383+0.000000j -0.562383+0.000000j   
499 -20.060297-0.000000j  ... -0.440730+0.000000j -0.440730+0.000000j   

                  10346               10347               10348  \
0   -0.322868-0.000000j -0.322868-0.000000j -0.322868-0.000000j   
1    0.513445-0.000000j  0.513445-0.000000j  0.513445-0.000000j   
2    0.833677-0.000000j  0.833677-0.000000j  0.833677-0.000000j   
3    0.017143+0.000000j  0.017143+0.000000j  0.017143+0.000000j   
4    0.131045-0.000000j  0.131045-0.000000j  0.131045-0.000000j   
..                  ...                 ...                 ...   
495 -0.408800-0.000000j -0.408800-0.000000j -0.408800-0.000000j   
496  0.951863-0.000000j  0.951863-0.000000j  0.9

In [31]:
total_col=df1.sum(axis=0)
total_row=df1.sum(axis=1)
total=total_col.sum()
den=np.outer(total_row,total_col)/total
df1=df1/den
df1

0                   1                   2      \
0   -0.421730+0.001474j  0.372198-0.000544j  0.902108-0.000521j   
1   -0.697288+0.002438j  0.578756-0.000846j  1.677895-0.000970j   
2   -0.544153+0.001902j  0.477750-0.000698j -0.064695+0.000037j   
3   -0.554820+0.001940j  0.322917-0.000472j  0.942801-0.000545j   
4   -0.384851+0.001345j  0.336361-0.000492j  0.643388-0.000372j   
..                  ...                 ...                 ...   
495 -0.371558+0.001299j  0.549981-0.000804j  0.798998-0.000462j   
496 -0.521207+0.001822j  0.338173-0.000494j  0.825655-0.000477j   
497 -0.433595+0.001516j  0.352598-0.000515j  0.829543-0.000480j   
498 -0.470474+0.001645j  0.434310-0.000635j  0.972589-0.000562j   
499 -0.477505+0.001669j  0.315422-0.000461j  0.939439-0.000543j   

                  3                   4                   5      \
0    1.024155-0.000353j -0.328719+0.000630j  1.148631+0.001829j   
1    0.840281-0.000290j -1.337067+0.002563j -1.365801-0.002174j   
2    1.117259-0.000385j -0.524130+0.001005j  1.125674+0.001792j   
3    1.095912-0.000378j -0.244331+0.000468j  1.300931+0.002071j   
4    1.257223-0.000433j  0.175827-0.000337j  0.908131+0.001446j   
..                  ...                 ...                 ...   
495  1.145169-0.000395j -1.381387+0.002648j  1.046711+0.001666j   
496  1.269372-0.000437j -0.464957+0.000891j  1.223687+0.001948j   
497  1.189425-0.000410j -0.549278+0.001053j  1.165317+0.001855j   
498  1.094069-0.000377j -0.147214+0.000282j  1.074630+0.001711j   
499  1.062109-0.000366j -0.613677+0.001176j  1.238100+0.001971j   

                   6                   7                   8      \
0    12.896837+0.208077j  0.868842-0.000289j  0.806399-0.000343j   
1    30.781723+0.496631j  0.373679-0.000124j  1.028814-0.000438j   
2    12.385434+0.199826j  0.926428-0.000309j  0.918681-0.000391j   
3     2.477572+0.039973j  0.897340-0.000299j  1.019647-0.000434j   
4    12.286594+0.198231j  0.730852-0.000243j  1.326769-0.000564j   
..                   ...                 ...                 ...   
495  10.881047+0.175554j  0.880942-0.000293j  1.069683-0.000455j   
496  15.211823+0.245427j  0.847753-0.000282j  0.768884-0.000327j   
497   9.845908+0.158853j  0.864100-0.000288j  0.944772-0.000402j   
498   8.179181+0.131963j  0.955946-0.000318j  0.984624-0.000419j   
499  16.307877+0.263111j  0.937334-0.000312j  1.034783-0.000440j   

                  9      ...               10344               10345  \
0    0.902483-0.000827j  ... -0.412266-0.000893j -0.412266-0.000893j   
1    0.399323-0.000366j  ... -2.386277-0.005166j -2.386277-0.005166j   
2    0.957712-0.000877j  ... -0.547954-0.001186j -0.547954-0.001186j   
3    0.896587-0.000821j  ... -0.048762-0.000106j -0.048762-0.000106j   
4    0.350679-0.000321j  ... -2.870022-0.006213j -2.870022-0.006213j   
..                  ...  ...                 ...                 ...   
495  0.967712-0.000887j  ... -2.016453-0.004366j -2.016453-0.004366j   
496  0.721410-0.000661j  ... -2.989721-0.006473j -2.989721-0.006473j   
497  0.935639-0.000857j  ... -1.075897-0.002329j -1.075897-0.002329j   
498  1.064533-0.000975j  ... -0.969632-0.002099j -0.969632-0.002099j   
499  0.981324-0.000899j  ... -0.853879-0.001849j -0.853879-0.001849j   

                  10346               10347               10348  \
0   -0.412266-0.000893j -0.412266-0.000893j -0.412266-0.000893j   
1   -2.386277-0.005166j -2.386277-0.005166j -2.386277-0.005166j   
2   -0.547954-0.001186j -0.547954-0.001186j -0.547954-0.001186j   
3   -0.048762-0.000106j -0.048762-0.000106j -0.048762-0.000106j   
4   -2.870022-0.006213j -2.870022-0.006213j -2.870022-0.006213j   
..                  ...                 ...                 ...   
495 -2.016453-0.004366j -2.016453-0.004366j -2.016453-0.004366j   
496 -2.989721-0.006473j -2.989721-0.006473j -2.989721-0.006473j   
497 -1.075897-0.002329j -1.075897-0.002329j -1.075897-0.002329j   
498 -0.969632-0.002099j -0.969632-0.002099j -0.969632-0.

In [32]:
ppmi=df1
ppmi[ppmi<0]=1e-10
ppmi=np.log(df1)
ppmi[ppmi<0]=0
ppmi.fillna(0)
ppmi

0         1                   2                   3         4      \
0    0.0+0.0j  0.0+0.0j  0.000000+0.000000j  0.023868-0.000345j  0.0+0.0j   
1    0.0+0.0j  0.0+0.0j  0.517540-0.000578j  0.000000+0.000000j  0.0+0.0j   
2    0.0+0.0j  0.0+0.0j  0.000000+0.000000j  0.110878-0.000345j  0.0+0.0j   
3    0.0+0.0j  0.0+0.0j  0.000000+0.000000j  0.091587-0.000345j  0.0+0.0j   
4    0.0+0.0j  0.0+0.0j  0.000000+0.000000j  0.228905-0.000345j  0.0+0.0j   
..        ...       ...                 ...                 ...       ...   
495  0.0+0.0j  0.0+0.0j  0.000000+0.000000j  0.135552-0.000345j  0.0+0.0j   
496  0.0+0.0j  0.0+0.0j  0.000000+0.000000j  0.238523-0.000345j  0.0+0.0j   
497  0.0+0.0j  0.0+0.0j  0.000000+0.000000j  0.173470-0.000345j  0.0+0.0j   
498  0.0+0.0j  0.0+0.0j  0.000000+0.000000j  0.089904-0.000345j  0.0+0.0j   
499  0.0+0.0j  0.0+0.0j  0.000000+0.000000j  0.060257-0.000345j  0.0+0.0j   

                  5                   6         7                   8      \
0    0.138572+0.001592j  2.557112+0.016133j  0.0+0.0j  0.000000+0.000000j   
1    0.000000+0.000000j  3.427051+0.016133j  0.0+0.0j  0.028407-0.000425j   
2    0.118383+0.001592j  2.516651+0.016133j  0.0+0.0j  0.000000+0.000000j   
3    0.263081+0.001592j  0.907409+0.016133j  0.0+0.0j  0.019456-0.000425j   
4    0.000000+0.000000j  2.508639+0.016133j  0.0+0.0j  0.282747-0.000425j   
..                  ...                 ...       ...                 ...   
495  0.045654+0.001592j  2.387153+0.016133j  0.0+0.0j  0.067362-0.000425j   
496  0.201870+0.001592j  2.722203+0.016133j  0.0+0.0j  0.000000+0.000000j   
497  0.152994+0.001592j  2.287186+0.016133j  0.0+0.0j  0.000000+0.000000j   
498  0.071978+0.001592j  2.101722+0.016133j  0.0+0.0j  0.000000+0.000000j   
499  0.213579+0.001592j  2.791778+0.016133j  0.0+0.0j  0.034192-0.000425j   

                  9      ...     10344     10345     10346     10347  \
0    0.000000+0.000000j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
1    0.000000+0.000000j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
2    0.000000+0.000000j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
3    0.000000+0.000000j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
4    0.000000+0.000000j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
..                  ...  ...       ...       ...       ...       ...   
495  0.000000+0.000000j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
496  0.000000+0.000000j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
497  0.000000+0.000000j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
498  0.062537-0.000916j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
499  0.000000+0.000000j  ...  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   

        10348     10349     10350     10351     10352     10353  
0    0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  
1    0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  
2    0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  
3    0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  
4    0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  
..        ...       ...       ...       ...       ...       ...  
495  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  
496  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  
497  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  
498  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  
499  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  

[500 rows x 10354 columns]