In [1]:
import pandas as pd 
import numpy as np 

In [2]:
# import dataset from sklearn
from sklearn.datasets import load_iris
dataset=load_iris()

In [3]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df['target'] = dataset.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [4]:
X=df.iloc[:,:-1]
p1=df[df.target==0]
p2=df[df.target==1]
p3=df[df.target==2]

In [5]:
w1=p1.iloc[:,:-1]
w2=p2.iloc[:,:-1]
w3=p3.iloc[:,:-1]

In [6]:
mu1 = w1.mean().values.reshape(1, 4)
mu2 = w2.mean().values.reshape(1, 4)
mu3 = w3.mean().values.reshape(1, 4)
mu = X.mean().values.reshape(1, 4)
n1=len(w1)
n2=len(w2)
n3=len(w3)

In [7]:
sb1 = n1*(mu1-mu).T.dot((mu1-mu))
sb2 = n2*(mu2-mu).T.dot((mu2-mu))
sb3 = n3*(mu3-mu).T.dot((mu3-mu))
sb=sb1+sb2+sb3
print(sb)

[[ 63.21213333 -19.95266667 165.2484      71.27933333]
 [-19.95266667  11.34493333 -57.2396     -22.93266667]
 [165.2484     -57.2396     437.1028     186.774     ]
 [ 71.27933333 -22.93266667 186.774       80.41333333]]


In [8]:
d1=w1-mu1
d2=w2-mu2
d3=w3-mu3


In [9]:
sw1=d1.T.dot(d1).values
sw2=d2.T.dot(d2).values
sw3=d3.T.dot(d3).values
sw=sw1+sw2+sw3
print(sw)

[[38.9562 13.63   24.6246  5.645 ]
 [13.63   16.962   8.1208  4.8084]
 [24.6246  8.1208 27.2226  6.2718]
 [ 5.645   4.8084  6.2718  6.1566]]


In [10]:
scatter_matrix = np.linalg.inv(sw).dot(sb)


In [11]:
eigenvalues, eigenvectors = np.linalg.eig(scatter_matrix)
print(eigenvalues)

[ 3.21919292e+01  2.85391043e-01 -1.60678244e-15 -9.19583748e-15]


In [12]:
#selecting first 2 eigenvalues corresponding eigenvectors are
v1=eigenvectors[:,0]
v2=eigenvectors[:,1]

In [13]:
y1 = pd.concat([w1.dot(v1),w1.dot(v2)],axis=1)
y2 = pd.concat([w2.dot(v1),w2.dot(v2)],axis=1)
y3 = pd.concat([w3.dot(v1),w3.dot(v2)],axis=1)
y=pd.concat([y1,y2,y3],axis=0)

In [14]:
df_reduced = pd.DataFrame(y.values, columns=['PC1', 'PC2'])
df_reduced['target'] = df['target']
df_reduced

PC1       PC2  target
0   -1.499210 -1.886754       0
1   -1.264360 -1.592143       0
2   -1.355253 -1.733415       0
3   -1.184956 -1.623588       0
4   -1.516956 -1.944762       0
..        ...       ...     ...
145  1.950586 -2.260018       2
146  1.833442 -1.706831       2
147  1.780129 -2.027876       2
148  2.011277 -2.440884       2
149  1.708503 -1.895322       2

[150 rows x 3 columns]